services:
  - type: web
    runtime: static
    name: vfarm-device-sdk-docs
    branch: main
    autoDeployTrigger: off
    buildCommand: pip install -e .[dev] && sphinx-build -W --keep-going -b html docs-site docs-site/_build/html
    staticPublishPath: docs-site/_build/html
